### ISSUE TITLE
Low-dependency GIT metadata

### ISSUE THREAD

**Issue by crepererum** [substrait-io/substrait-rs#100]
Does substrait really need to include a whole GIT stack (gix) just to be compiled? Could it maybe shell out to a CLI GIT implementation to perform that work (which you need anyways just to clone the repo)? See #97 as well. Another option would be to pre-build the relevant `src/version.in` and add this to the repo (that would have slightly less information, like the `dirty` would be missing, but this seems still be good enough for most people, esp. when you just pull substrait is an indirect dependency).

**Comment by mbrobbel** [comment]
No we don't really need it. So yes, we can drop that dependency and use git directly. I can provide a patch next week.
