### ISSUE TITLE
Add unsigned-integer type variations

### ISSUE THREAD

**Issue by waynexia** [substrait-io/substrait-rs#17]
Substrait native integer types only have those signed like `i8`, `i32` or `i64`. But I think it is a common requirement to use `u8`, `u32` and `u64` in rust (and maybe other) systems. Looks like substrait used to contain those types but I've not found out why they are removed.

After some reading on the docs I think we can define these types as "type variation" and add a yaml document for them. So how about define them here, and maybe also add some convenient util functions (like getter or setter to the encoded literal) to those types?

(Maybe I'm on the totally wrong way of defining unsigned integers, please do let me know if so 🤕)

**Comment by mbrobbel** [comment]
There was a discussion about this in https://github.com/substrait-io/substrait/discussions/2#discussioncomment-1297609, and they were removed in https://github.com/substrait-io/substrait/pull/18 and https://github.com/substrait-io/substrait/pull/25.

**Comment by waynexia** [comment]
Thanks for your information, I only find the last two links 😀

So the encouraged way is to define these kinds of variant in where they would be used. And since this repo is an official one so it wouldn't add these types.

But I would say that the selection over *Spark, Trino, Iceberg and Arrow* are not fair... Only Arrow of these four are not start from JAVA/Scala (I'd classify it to C/C++), the unsigned type would of course loss the battle.

Anyway thanks again, my doubt on this question is solved :D
