### ISSUE TITLE
Release automation and commit message conventions

### ISSUE THREAD

**Issue by mbrobbel** [substrait-io/substrait-rs#38]
Following [substrait](https://github.com/substrait-io/substrait) and [substrait-java](https://github.com/substrait-io/substrait-java) (and with the plan for the validator in https://github.com/substrait-io/substrait-validator/issues/4) I would like to propose to setup release automation for this repository using [semantic-release](https://github.com/semantic-release/semantic-release) and [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

@jacques-n @andygrove you are listed as the crate owners on crates.io, how do you feel about this? Would you be willing to provide an API token for crates.io (add this as secret in this repo) to publish those releases?

I can contribute the PRs to enable these changes.

**Comment by andygrove** [comment]
+1 for release automation following the approach uses in the other repos here.

> Would you be willing to provide an API token for crates.io (add this as secret in this repo) to publish those releases?

Sure, if you can give me instructions on how to add as a secret here.

**Comment by mbrobbel** [comment]
@andygrove can you please add a crates.io token (with permissions to publish the substrait crate) secret named `CRATES_IO_TOKEN`? The steps to add a secret are listed [here](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository).

**Comment by andygrove** [comment]
> @andygrove can you please add a crates.io token (with permissions to publish the substrait crate) secret named `CRATES_IO_TOKEN`? The steps to add a secret are listed [here](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository).

I don't have the necessary permissions to do this. Maybe @jacques-n can help with this.
